spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/menu_connect_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Faz o Hibernate criar e atualizar as tabelas automaticamente baseado no código Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Hibernate está rodando por baixo dos panos
spring.jpa.show-sql=true